[package]
name = "bookkeeper-rs"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
protobuf-codegen-pure = "2.14"